### ISSUE TITLE
Expose version as separate output

### ISSUE THREAD

**Issue by eshepelyuk** [TheRealWaldo/release-it#90]
### Motivation

Currently the action exposes only single output as JSON string.
This is not really convenient because requires parsing of JSON to access new version in subsequent steps.

### Proposal

Create dedicated output named version and expose new version there after step completion.

### Result

Instead 

```
- name: release-it
  id: releaseIt
  uses: TheRealWaldo/release-it@v0.1.1
  with:
    json-opts: '{"dry-run": true}'
- run: echo ${{ fromJson(steps.releaseIt.outputs.json-result).version }}
```

One could write 

```
- name: release-it
  id: releaseIt
  uses: TheRealWaldo/release-it@v0.1.1
  with:
    json-opts: '{"dry-run": true, "ci": true}'
- run: echo ${{ steps.releaseIt.outputs.version }}
```
